### ISSUE TITLE
iFrame and data attributes

### ISSUE THREAD

**Issue by Barzille** [noelboss/featherlight#120]
I try to set up an iFrame and define width and height via the data attributes as seen in this fiddle:

http://jsfiddle.net/uw4hdwfg/1/

But the iFrame will always stay at the same size.
Can you help me and tell me what I am doing wrong?

**Comment by marcandre** [comment]
Use `data-iframe-height`

**Comment by Barzille** [comment]
This doesnt seem to work: See this http://jsfiddle.net/uw4hdwfg/2/

**Comment by marcandre** [comment]
Oups, sorry, it's `data-featherlight-iframe-height`

**Comment by Barzille** [comment]
That looks much better, thank you.
Is it intended that the lightbox is showing up at a small width and height before the iframe is completely loaded?

**Comment by marcandre** [comment]
While it loads, you might want to consider adding a spinner, see [#108]

**Comment by jdev-d** [comment]
Its not working on my website... Any ideas?

**Comment by orugari** [comment]
Not working with %, options not working.

**Comment by Sartory** [comment]
Trying to set a flexible data-featherlight-iframe-width for a responsive design.
It's not working with `data-featherlight-iframe-width="90%"` or `data-featherlight-iframe-width="90vw"`

Any ideas?

**Comment by leoarce** [comment]
No iframe responsive/fluid width, like @Sartory was asking? Also I see bug when link is put into the DOM via jQuery, it takes a double click to open the iframe. First click will give this error: Featherlight: no content filter found  (no target specified). Not finding solutions for this anywhere.

**Comment by Pretobrazza** [comment]
me neither I'm finding a solution for the iframe responsive/fluid width nor the double click to open the iframe. Opening with a ajax is not an option as both text from the <head> as from a 'leaflet maps' script are populating the top and bottom in the modal pane.

**Comment by pauloamorimbr** [comment]
About the double click...I solved it by calling it manually on a jquery.click event instead of letting the featherlight do the work. Worked like a charm

**Comment by marcandre** [comment]
For the 'width' issue, FL now distinguishes CSS attributes from HTML attributes, so shouldn't be an issue anymore.
Not sure I understand the "double click" issue. Ideally, someone would open a different issue and post a working example.

**Comment by richardtallent** [comment]
Having the same problem here. My live site exhibits this issue. First click gives an "no content filter" error in the console, second click works.

**PLEASE NOTE: I'm an art photographer, my site contains nudity, so this link is NSFW:** 
https://www.tallent.us/gallery.html?show=glassdarkly

As far as I know, the only thing I just changed that may have impacted the functionality is migrating from Riot.js to Vue.js for rendering the gallery. I also upgraded featherlight to the latest version yesterday, but I believe it was working then.

**Comment by richardtallent** [comment]
I'm not sure why, but moving this code to run within Vue's "update" event (i.e., after the DOM has been loaded/patched) seems to have fixed the issue.

```
$(document).on('click', '.featherlight [data-featherlight]', function(evt) {
	evt.stopImmediatePropagation();
});
```

I get the impression this may be a side-effect, because the purpose of that code isn't to initialize Featherlight, it's to ensure that the user doesn't click the large preview shown in the featherlight modal and create another modal.

(In my application, the DOM shown in the modal is hidden by default, but is also available to the user in a long list if they use the "feed" view. In "feed" view, the photos can still be clicked to load in featherlight in a larger size, but the src is the same for both the feed and the modal. Hope that explains things...)

**Comment by marcandre** [comment]
@richardtallent I was able to find a bug that would screw up the first click of dynamically loaded content. Try the latest release.
FWIW, this has nothing to do with the current issue (there no iframe, etc...)

**Comment by richardtallent** [comment]
@marcandre, I think that fixed it, thanks! The fix I wrote about above wasn't consistent, so I must've just been experiencing an intermittent issue.

**Comment by cibulka** [comment]
"First click issue" issue persists for me - specifically with the version `1.7.6` and dynamically loaded images.

```
<div id="ajax-gallery">
  <div class="js-gallery" data-featherlight-gallery data-featherlight-filter="a">
    <a href="http://example.com/image.jpg"><img src="http://example.com/image.jpg" /></a>
  </div>
</div>
```
First click => 

```
Featherlight: no content filter found  (no target specified)
```

Second click works.

---

Is there maybe some way, how to manually refresh Featherlight bindings? Maybe I've just overlooked it in the documentation.

Thanks a lot, P!

**Comment by marcandre** [comment]
@cibulka Could you please provide a working example so I can look at it? And open an new issue, since it is not related to the original one.

**Comment by cibulka** [comment]
@marcandre Thanks for a fast reply! It seemed to me, that the issue was actually related (dynamically loaded content, works on second click, etc.), that's why I posted here.

I could not reproduce the issue on js-fiddle though, so it seems, that there is some problem with my code.

I will try to dig in Featherlight (and in my code) some more and whenever I will have more time (and know more), I will open new issue.

P!
