### ISSUE TITLE
Can't prevent opening lightbox with beforeOpen returning false

### ISSUE THREAD

**Issue by IrinaStr** [noelboss/featherlight#202]
Hi,

I try to prevent opening the lightbox when a div has the class 'disabled' but I can't bring it to work. What is wrong here?: 

```
$('#myDiv').featherlight({
        beforeOpen: function(event){
           if ($('#myOtherDiv').hasClass('disabled')) {
             return false;
           } else {
                //do something else and open featherlight window
           }
        }
 });
```

I also tried this to see if something is wrong with my if clause, but without any luck:

```
$('#myDiv').featherlight({
        beforeOpen: function(event){
           return false;
        }
 });
```
The lightbox still opens every time..

**Comment by marcandre** [comment]
The error is in your code somehow. Without a complete working example, I can't help you. Maybe you already have `data-featherlight` in your HTML, that will do the binding without a `beforeOpen` first?

This is a good example why we ask to provide a working jsfiddle in our Contributions Guidelines. When people don't, we have to do it instead, and it can be especially frustrating when it turns out that the feature [works as expected](http://jsfiddle.net/r37vm0o8/).

In the future, please provide complete examples and not just for Featherlight but for any open source project.
