### ISSUE TITLE
Featherbox Shows all Scripts and CSS in ajax request

### ISSUE THREAD

**Issue by Doxramos** [noelboss/featherlight#230]
What kind of issue is this? (put 'x' between the square brackets)
- [ x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
     starting from http://jsfiddle.net/JNsu6/15/ .
  Featherbox shows all your inline javascript and css on ajax requests

**Comment by realmalcolm** [comment]
I have the same issue. All of my javascript code which I've added in a `<style>`-Tag is visible.

**Comment by marcandre** [comment]
Featherlight calls `jquery`'s [`load`](http://api.jquery.com/load/)
Maybe you simply need to specify a selector after the url (separated by a space)?

Again, as usual, without a working example it's very difficult to address an issue

**Comment by versantweb** [comment]
That's true, I also have this problem. 

I load an ajax page from featherlight. On this page I use javascript to change selectbox in a better display. So, the javascript works, but it's also displayed on HTML because the class ".featherlight-inner" is aded to the "<script>" tage like this : 

<script class="featherlight-inner">
	$("select[name='miki-snippet']").niceSelect();
</script>

Because this class has a "display: block" style, the script is displayed as text.

**Comment by marcandre** [comment]
@versantweb: I can imagine plenty of solutions. One is to simply override the css for `<script>`:

    script.featherlight-inner { display: none }

Other easy solution would be to wrap your script and content in a `<div>`?

```
<div class="complete-content">
  <script>...</script>
  <style>...</style>
  <p>Actual content</p>
</div>
```

**Comment by versantweb** [comment]
I took off the javascript and put it into the "afterOpen" function

So it's working now.

But your solutions would also work. Specially the second, but didn't test.

**Comment by darkain** [comment]
I just ran into this issue tonight, too. script.featherlight-inner isn't targeted enough to override the default CSS. Below is the CSS I'm using right now, and think it might be wise to add it into the main code base.

```css
script.featherlight-inner,
style.featherlight-inner {
	display:none !important;
}
```

**Comment by marcandre** [comment]
Ok, I've added a rule to avoid showing `<style>` and `<script>`...

**Comment by darkain** [comment]
```css
	.featherlight script.featherlight-inner,
	.featherlight style.featherlight-inner {
		display: inherit;
	}
```
This doesn't resolve the issue. This just tells the <script> and <style> tags to inherit the display property from their parent object which is "display:inline-block" from < div class="featherlight-content" >. In theory, it SHOULD be set to "initial", but at least Blink is then using "display:block" instead of "display:none". The only solution I've found is to force it to "display:none" specifically. 

Also note, the HTML5 spec lists several more elements that should be hidden by default, too. 

https://www.w3.org/TR/2014/REC-html5-20141028/rendering.html#hidden-elements

Curious: Is there a particular reason why each of the root elements added to the Featherlight model need "display:block" in the first place? I'm guessing this has to deal with popping in hidden content elsewhere on the DOM from the same page? Is there a particular way to override adding the "featherlight-inner" class to elements from Ajax requests? Forcing content into "display:block" mode doesn't seem like the best idea, considering the amount of content that is using "display:flex" as well now.

**Comment by marcandre** [comment]
Oops. Confused it with `initial` (clearly, CSS is not my forte), sorry. Changed to `hidden`, which is just clearer anyways.

It probably was a bad idea to have `featherlight-inner` be shown like this. The idea was that users could have `display:none` on some content and still put it in a featherlight, but the solution should have been to force the user to wrap the content in a `display:none` originally, or have the rules hidding it be `not(.featherlight-inner)` or something.

Changing this would imply a major version release though :-( as it would be a clear source of incompatibility. Opinions on if it's worth it or not?

In the meantime at least, I'll try to fix this for the most likely sources of issues.

**Comment by marcandre** [comment]
PS @darkain: Featherlight relies on the `-inner` class for cleanup, so that can't go away, but you are welcome to override that particular rule

**Comment by darkain** [comment]
It should be "display:none", not "display:hidden" - "hidden" is for the visibility property, but that wouldn't work here, because visibility still occupies visual space whereas "display:none" disables all rendering. A simple list of all of the display rules can be found here for reference: https://www.w3schools.com/cssref/pr_class_display.asp

**Comment by marcandre** [comment]
:bomb: Argh 😭  Fixed
