### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by michaelchristian** [noelboss/featherlight#26]
I was wondering how to add manual close button within featherlight modal window in addition to standard 'x'  

```
<span class="featherlight-close">✕</span>
```

```
 <a href="javascript:void(0)" onclick="?????">Close</a>
```

Much appreciated

**Comment by chrisandtre** [comment]
HI, i'm using a lightbox that will basically fill the screen, and when using a mobile, you expect to use your back button to close the box. Any easy way to accomplish that via onKeyPress, to include the android back button?
otherClose?
Very new to JS but a dedicated learner.

**Comment by marcandre** [comment]
@chrisandtre: it's good that you've searched the old issues. It's less a good idea to ask a question by posting here (a thread closed 4 years ago on a different issue) instead of following the guidelines in the [README](https://github.com/noelboss/featherlight#support) or opening a different issue. That being said, Featherlight doesn't support that, and the answer is that it's complicated and depends how (or if) you already handle state change. This [StackOverflow question](https://stackoverflow.com/questions/25806608/how-to-detect-browser-back-button-event-cross-browser) may be a good starting point. Good luck.

**Comment by chrisandtre** [comment]
Thanks Marcandre I realize now it's not as related as I had originally thought. Thanks for the feedback also, will look into it.
