### ISSUE TITLE
Multiple galleries on one page without unique classes

### ISSUE THREAD

**Issue by jacobraccuia** [noelboss/featherlight#271]
How can I call multiple galleries on a page without having to use unique classes?

I tried
```

if($('.image-gallery').length) {
		$('.image-gallery').featherlightGallery({
			variant: 'gal',
			filter: $(this).find('.featured-image') 
		});
}

```

but I don't think filter works the way I think it does.

Currently - it loads each item on the page in the same gallery lightbox.  I want a unique lightbox gallery for each parent ".image-gallery".  In otherwords, clicking the arrows in the first lightbox gallery should not show me photos from the second one.

```
<div class="image-gallery">
     <div class="featured-image" data-featherlight="http://imgurl"><img /></div>
     <div class="featured-image" data-featherlight="http://imgurl"><img /></div>
</div>

<div class="image-gallery">
     <div class="featured-image" data-featherlight="http://imgurl"><img /></div>
     <div class="featured-image" data-featherlight="http://imgurl"><img /></div>
</div>


```

**Comment by marcandre** [comment]
Hi!

My name is Marc-André and **I'd like your help**. I'm not the original author but I liked the project so much I started contributing more and more; now I'm the (only) maintainer.

#### How you can help

I'd like **you to help me** in keeping the issues of this project organized. In particular, I'd very much like questions to be asked on [Stack Overflow](http://stackoverflow.com)(reasons just down below) and I think **you could help**.

To serve that goal, I wrote that questions should be asked on [Stack Overflow](http://stackoverflow.com) in the [READ ME](https://github.com/noelboss/featherlight#questions) file. Still, some people asked questions here.

I requested the same in the [Contributing Guidelines](https://github.com/noelboss/featherlight/blob/master/.github/CONTRIBUTING.md). Even though GitHub has a paragraph saying "Please review the guidelines for contributing to this repository." that shows up whenever someone creates an issue, some people still asked questions here.

Finally, GitHub allowed us to write a template issue, in which I wrote
> This issue tracker is not the place for questions. If you want to ask how to do
> something, or to understand why something isn't working the way you expect it to, use
> http://stackoverflow.com/questions/ask .
> Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
> We monitor the tag `featherlight.js`.

Still, some people like you delete this text and ask a question here. So my question is: **why did you feel it was the right thing to do**? What could I possibly have done so that this basic wish was respected? I must admit that I feel disrespected whenever someone completely ignores my requests. I understand that most developers don't feel the urge to help by digging in, inspecting the code and contributing back with great bug reports or pull requests, but it saddens me when people show little care and disregard maintainer wishes.

It would help me a lot if you helped me find a solution so that questions are asked on [Stack Overflow](http://stackoverflow.com).

#### Why StackOverflow?

I feel that [StackOverflow](http://stackoverflow.com) is much better organized for questions and answers than GitHub. Not too surprising, that's exactly what it was designed for!

It has a much better interface to find similar questions, so there's a better chance a question and its answers will help someone else.

I monitor the tag for this project, so I normally will read the question. Sometimes, someone else has already answered the question, which is awesome for whoever wrote the question and for me! That never happens with GitHub issues, btw.

Otherwise I can answer it, especially if it shows what the requester has tried, and has a working example. If something is not clear, there's the comment section, that insure that the discussion doesn't have to be re-read by others that only want the answer.

If the question is badly asked, for example if it has no [working example](http://jsfiddle.net/JNsu6/15/), I can also ignore it and downvote it. Maybe someone will answer it, either way, I don't have an opened issue being stale in GitHub forever.

Indeed, I try as best as I can to keep the list of open GitHub issues down to a minimum. Things there should mostly be things that need to be fixed one way or another. Having a bunch of half baked questions in there would not help at all.

I'm hoping you will reply with good hints on how to achieve this goal. Thanks.

**Comment by jacobraccuia** [comment]
Hi!

I'm sorry you feel disrespected / regarded.  I didn't ask my question on Stack Exchange because I felt like my issue wasn't simply "how do I do this with JS and HTML please help!".  (I mean maybe it is).

The truth is I find the documentation here to be difficult to understand.  I've spent a lot of time (not close to the amount of time you've spent maintaining and writing such a great plugin), but time nonetheless trying to understand just how I can achieve the things I want to achieve. 

So I guess I wrote this here because I believe that this is a bug (or feature request) in the way the lightbox gallery works, and not just a "how do I do this?".  Whether the gallery respects the parent container or not should, I guess ultimately be a user decision.

So why didn't I write on Stack Exchange?  I saw a few questions re: featherlight and I guess I was worried that it would just go unanswered into the abyss of unanswered questions. ( I have a few there, and I know that I wanted a response as soon as possible ).  

I didn't intend to disrespect you and I blatantly did by ignoring the template github provides.  I can make excuses like I did above, but I'm sorry nonetheless for ignoring your wishes.

I will paste my question on SE and hopefully you'll forgive me and help out, or someone else will, which is the great thing about SE!
