### ISSUE TITLE
Can you help? How can I trigger an event (e.g. play a stopped video) when a featherlight window is being closed (click on on the close button)? 

### ISSUE THREAD

**Issue by ltsally** [noelboss/featherlight#336]
Can you please help? How can I trigger an event when a featherlight popup is being closed? I want to stop a video when popup opens and play it when popup is being manually close.

**Comment by marcandre** [comment]
Hi!

My name is Marc-André. I'm not the original author but I liked the project so much I started contributing more and more; now I'm the (only) maintainer.

This looks like a question. You may not have realized it, but asking questions here is not the best way to go. Actually, it's against my wishes. For this project, Github issues are only for bugs and pull requests. 

#### "So what should I do?"

First, you might want to consider the fact that you didn't take enough care before posting this question here. I wrote about how questions should be asked in the [READ ME](https://github.com/noelboss/featherlight#questions) file. I requested the same in the [Contributing Guidelines](https://github.com/noelboss/featherlight/blob/master/.github/CONTRIBUTING.md). When you opened this issue, GitHub has a paragraph saying "Please review the guidelines for contributing to this repository." at the very top. Finally, GitHub allowed us to write a template issue, in which I wrote
> This issue tracker is not the place for questions. If you want to ask how to do
> something, or to understand why something isn't working the way you expect it to, use
> http://stackoverflow.com/questions/ask .
> Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
> We monitor the tag `featherlight.js`.

All that to say: posting a question here despite all this isn't very respectful.

Yes, sure, I understand, you have a problem, and you want to get it fixed yesterday. I'm trying to help you by asking you to deepen your understanding in open source in general. To get your issue resolved, you might need to spend more time understanding things.

#### "But really, what should I do?"

You should do what you should have done in the first place, which is to follow the requests in the Contributing guidelines:

For questions, please use [Stack Overflow](http://stackoverflow.com/questions/ask) and be sure to use the `featherlight.js` tag. Please **provide an example**, starting for example from [this jsfiddle](http://jsfiddle.net/JNsu6/15/)

#### "But why StackOverflow?""

I feel that [StackOverflow](http://stackoverflow.com) is much better organized for questions and answers than GitHub. Not too surprising, that's exactly what it was designed for!

It has a much better interface to find similar questions, so there's a better chance a question and its answers will help someone else.

I monitor the tag for this project, so I normally will read the question. Sometimes, someone else has already answered the question, which is awesome for whoever wrote the question and for me! That never happens with GitHub issues, btw.

Otherwise I can answer it, especially if it shows what the requester has tried, and has a working example. If something is not clear, there's the comment section, that insure that the discussion doesn't have to be re-read by others that only want the answer.

If the question is badly asked, for example if it has no [working example](http://jsfiddle.net/JNsu6/15/), I can also ignore it and downvote it. Maybe someone will answer it, either way, I don't have an opened issue being stale in GitHub forever.

Indeed, I try as best as I can to keep the list of open GitHub issues down to a minimum. Things there should mostly be things that need to be fixed one way or another. Having a bunch of half baked questions in there would not help at all.

I'm hoping you will reply with good hints on how to achieve this goal. Thanks.
