### ISSUE TITLE
No place to ask questions ?

### ISSUE THREAD

**Issue by LMS007** [noelboss/featherlight#343]
stackoverflow.com 

^ lol, thats not a solution.

**Comment by marcandre** [comment]
Hi!

My name is Marc-André. I'm not the original author but I liked the project so much I started contributing more and more; now I'm the (only) maintainer.

I feel that [StackOverflow](http://stackoverflow.com) is much better organized for questions and answers than GitHub. Not too surprising, that's exactly what it was designed for!

It has a much better interface to find similar questions, so there's a better chance a question and its answers will help someone else.

I monitor the tag for this project, so I normally will read the question. Sometimes, someone else has already answered the question, which is awesome for whoever wrote the question and for me! That never happens with GitHub issues, btw.

Otherwise I can answer it, especially if it shows what the requester has tried, and has a working example. If something is not clear, there's the comment section, that insure that the discussion doesn't have to be re-read by others that only want the answer.

If the question is badly asked, for example if it has no [working example](http://jsfiddle.net/JNsu6/15/), I can also ignore it and downvote it. Maybe someone will answer it, either way, I don't have an opened issue being stale in GitHub forever.

Indeed, I try as best as I can to keep the list of open GitHub issues down to a minimum. Things there should mostly be things that need to be fixed one way or another. Having a bunch of half baked questions in there would not help at all.
