### ISSUE TITLE
[Bug] "wp_featherlight_disable" custom metadata always added

### ISSUE THREAD

**Issue by elosha** [noelboss/featherlight#403]
Hey,

Featherlight always adds/suggests a custom metadata value to any post that is edited:
"wp_featherlight_disable". Even if this is removed, it will be shown again next time.

This is quite annoying if you are using custom metadata.

If you fear that users could miss how to disable featherlight, add a simple Featherlight GUI box to the editor that offers a "Disable" checkbox and that can be hidden.

I wrote a plugin where I needed to add boolean metadata, similar to this case. I made a simple GUI box with radio buttons and chose to only save the metadata value if it was non-empty and non-default. Otherwise the metadata value would be removed.

This also keeps the DB clean :)

Regards
E

**Comment by marcandre** [comment]
Thanks for the report. I can help you with bugs of `Featherlight` the javascript library, but I'm not quite familiar with the WordPress plugin that encapsulate it. The name `wp_featherlight_disable` suggest that your issue is with that plugin and not the library.

Could you please open an issue there instead?
